# Site settings
title: "Stembolt"
email: hello@stembolt.co
url: http://stembolt.co
description: "Ruby on Rails + Spree Commerce development shop. We build high performance, scalable applications."
skills: "Spree ecommerce, Managed Services + DevOps, High Performance & Scalability e Application Development"
meta_author: Pedro D.

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5fbffd #80B3FF
  primary-rgb: 5fbffd #"128,179,255"
  secondary: 3e3e3e #FD6E8A
  secondary-dark: 3e3e3e #A2122F

# Footer settings
footer:
  copyright: Stembolt.co
  location: Location
  social: Around the Web
  credits: Start a Project

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/stemboltco
  - title: facebook
    url: http://facebook.com/stemboltco
  - title: github
    url: http://github.com/stemboltco
# Postal address (add as many lines as necessary)
address:
  - line: contact@stembolt.co
  - line: (+351) 91 663 9929
# Credits content
credits: "Stembolt.co"

# Build settings
markdown: kramdown
permalink: pretty
